version: '3'

services:    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    networks: 
      - gmauricio-network

  api:
    build:
      dockerfile: ./docker/api.dockerfile
      context: .
    image: gmauricio/api
    container_name: api
    ports: 
      - 8080:8080
    environment: 
      HOST_MONGO: mongo 
    networks: 
      - gmauricio-network
    depends_on:
      - mongo   
    restart: on-failure:10

networks: 
  gmauricio-network:
    driver: bridge